<a href="https://colab.research.google.com/github/mightyhopes/AI-Learning-Journey/blob/main/02_Deep_Learning_Fundamentals/S5E1_PyTorch_Intro_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

print(f"Versi PyTorch: {torch.__version__}")

Versi PyTorch: 2.10.0+cu128


In [ ]:
# 1. Skalar (Tensor Orde 0 / Dimensi 0)
skalar = torch.tensor(5)
print("Skalar:\n", skalar, "| Dimensi:", skalar.shape)

# 2. Vektor (Tensor Orde 1 / Dimensi 1)
vektor = torch.tensor([1, 2, 3, 4, 5])
print("\nVektor:\n", vektor, "| Dimensi:", vektor.shape)

# 3. Matriks (Tensor Orde 2 / Dimensi 2)
matriks = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\nMatriks:\n", matriks, "| Dimensi:", matriks.shape)

# 4. Tensor 3D (Tensor Orde 3 / Dimensi 3) - Kumpulan Matriks
tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
print("\nTensor 3D:\n", tensor_3d, "| Dimensi:", tensor_3d.shape)

Skalar:
 tensor(5) | Dimensi: torch.Size([])

Vektor:
 tensor([1, 2, 3, 4, 5]) | Dimensi: torch.Size([5])

Matriks:
 tensor([[1, 2, 3],
        [4, 5, 6]]) | Dimensi: torch.Size([2, 3])

Tensor 3D:
 tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]) | Dimensi: torch.Size([3, 2, 2])


In [ ]:
# Membuat Numpy Array
array_numpy = np.array([[1, 2], [3, 4]])

# Mengubah Numpy ke PyTorch Tensor
tensor_pytorch = torch.tensor(array_numpy)
# Bisa juga menggunakan float tensor jika butuh koma (desimal)
tensor_float = torch.FloatTensor(array_numpy)

print("Numpy ke Tensor:\n", tensor_pytorch)
print("Tipe data float:\n", tensor_float)

# Mengubah kembali dari Tensor ke Numpy
balik_ke_numpy = tensor_pytorch.numpy()
print("\nKembali ke Numpy:\n", balik_ke_numpy)

# Mengambil nilai (value) asli Python dari Tensor yang isinya cuma 1 angka (Skalar)
angka_skalar = torch.tensor(100)
nilai_python = angka_skalar.item()
print("\nNilai Python murni (pakai .item()):", type(nilai_python), "->", nilai_python)

Numpy ke Tensor:
 tensor([[1, 2],
        [3, 4]])
Tipe data float:
 tensor([[1., 2.],
        [3., 4.]])

Kembali ke Numpy:
 [[1 2]
 [3 4]]

Nilai Python murni (pakai .item()): <class 'int'> -> 100


In [ ]:
# Misal kita punya data ukuran 3 Channel, 5 Baris (Height), 5 Kolom (Width)
# Total elemen = 3 x 5 x 5 = 75
tensor_awal = torch.rand(3, 5, 5)
print("Ukuran awal:", tensor_awal.shape)

# Meratakan (reshape) tensor menjadi 3 baris dan 25 kolom
tensor_view = tensor_awal.view(3, 25)
print("Ukuran setelah di-view:", tensor_view.shape)

Ukuran awal: torch.Size([3, 5, 5])
Ukuran setelah di-view: torch.Size([3, 25])


In [ ]:
# Cek ketersediaan GPU di Google Colab
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device yang digunakan: {device}")

# Membuat tensor baru
tensor_komputasi = torch.tensor([10, 20, 30])
print("\nSebelum pindah device:", tensor_komputasi.device)

# Memindahkan tensor ke GPU (jika tersedia) / duplikasi data dari RAM ke memori GPU
tensor_komputasi = tensor_komputasi.to(device)
print("Setelah pindah device:", tensor_komputasi.device)

Device yang digunakan: cuda

Sebelum pindah device: cpu
Setelah pindah device: cuda:0
